### ISSUE TITLE
Premium theme

### ISSUE THREAD

**Issue by websevendev** [semantic-ui-forest/awesome-semantic-ui#3]
Hello,

Is a premium WordPress theme that's using Semantic UI something that I could add to this list or do you want to keep it free stuff only?

Thanks

**Comment by xiaohanyu** [comment]
Could you show us a demo/link of your theme?

**Comment by websevendev** [comment]
https://chap.website

**Comment by xiaohanyu** [comment]
Is this free or commercial? If commercial, I think we can add a `Commercial` section which contains links to your site.

**Comment by websevendev** [comment]
Commercial

**Comment by xiaohanyu** [comment]
It's OK. Please propose a PR.

**Comment by websevendev** [comment]
Will do, thanks!
